### ISSUE TITLE
There are no jar file.

### ISSUE THREAD

**Issue by toprak** [Suwayomi/TachideskJUI#3]
Would you serve it please.

**Comment by BrandonKMLee** [comment]
maybe because the software is not ready for release yet? please check the Discord.

**Comment by toprak** [comment]
> maybe because the software is not ready for release yet? please check the Discord.

my bad.

**Comment by BrandonKMLee** [comment]
@toprak do you know how to compile a JAR tho? just wondering

**Comment by toprak** [comment]
@BrandonKMLee I could not see read me utterly, I followed instructions on the read me and it worked i guess.

**Comment by Syer10** [comment]
Ya JUI still has some things I need to work on before I would qualify it as able to be released, such as the reader and a few other things

**Comment by BrandonKMLee** [comment]
@Syer10 can't ask for a kanban like with https://github.com/Suwayomi/TachideskJUI/projects
but at least there is a hopeful timeframe release of Tachidesk.

**Comment by AriaMoradi** [comment]
> @Syer10 can't ask for a kanban like with https://github.com/Suwayomi/TachideskJUI/projects
> but at least there is a hopeful timeframe release of Tachidesk... right?

The kanban is not really reliable on predicting what's gonna be on the next version, but I think we can discuss it on discord

**Comment by Syer10** [comment]
I setup a kanban board, not sure how much I will use it
