### ISSUE TITLE
[Feature Suggestion] Auto resize pop ups

### ISSUE THREAD

**Issue by BaccanoMob** [Suwayomi/TachideskJUI#6]
For example,
![image](https://user-images.githubusercontent.com/82655889/121039091-14fa0300-c7b1-11eb-92b2-6bd3dfebe727.png)

It be good if the pop window covered all the options in the menu in a single go. 

Since the reader also opens as another window, an option to whether the window should fit to height or width or default size could be useful.

**Comment by BaccanoMob** [comment]
light mode as a shadow for the pop ups as soon here.
![image](https://user-images.githubusercontent.com/82655889/121040444-314a6f80-c7b2-11eb-9982-0015044e0af1.png)

It be cool to have something similar for the dark mode as well if possible.

**Comment by Syer10** [comment]
These dialogs will be re-worked into the compose window classes when Jetbrains Compose 0.5 hits, right now they are just a stopgap solution, so closing due to relevancy
