### ISSUE TITLE
[Feature Request] Provide an option in the settings to download comics to the Tachidesk-Server

### ISSUE THREAD

**Issue by Mister-album** [Suwayomi/TachideskJUI#77]
## What feature should be added to Tachidesk-JUI?
Provide an option in the settings to download comics to the Tachidesk-Server

##  Why/Project's Benefit/Existing Problem
Download the manga to Tachidesk-Server on the Android client instead of saving it to the phone, which can reduce the occupancy of the phone's storage and better manage the manga

**Comment by album-GitHub** [comment]
> Tachidesk-JUI 首先没有客户端下载。它保存图像的唯一地方是在读取时保存在中。所有下载均由Tachidesk-Server 处理。

Sorry, I didn't see the comic downloading on Tachidesk-Server the first time I downloaded it. But now, after reopening the app and trying to download it again, I can see that the comic is downloading. Thank you for your response.
